# Database configuration - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/car_db
spring.datasource.username=postgres
spring.datasource.password=12341
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.allow-bean-definition-overriding=true
# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Server
# Përdor portin që jep Render-i (PORT), ose 8080 si fallback
server.port=${PORT:8080}
# Dëgjo në të gjitha ndërfaqet e rrjetit që të jetë i aksesueshëm nga jashtë
server.address=0.0.0.0